version: "3"
services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
volumes:
  postgres-data:
  node-modules:
